-- Phase 23: multi-dataset join (materialize to biz_query_row)
-- Custom compound join keys via join_keys_json

CREATE TABLE IF NOT EXISTS biz_query_dataset (
  dataset_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  query_id int8 NOT NULL,
  dataset_code varchar(32) NOT NULL,
  dataset_name varchar(100) NOT NULL,
  is_primary char(1) DEFAULT '0',
  source_file varchar(255) DEFAULT NULL,
  sheet_name varchar(100) DEFAULT NULL,
  row_count int4 DEFAULT 0,
  headers_json text,
  sort int4 DEFAULT 0,
  create_time timestamp DEFAULT now(),
  update_time timestamp DEFAULT now(),
  PRIMARY KEY (dataset_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_biz_query_dataset_code ON biz_query_dataset(query_id, dataset_code);
CREATE INDEX IF NOT EXISTS idx_biz_query_dataset_qid ON biz_query_dataset(query_id);

CREATE TABLE IF NOT EXISTS biz_query_dataset_row (
  row_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dataset_id int8 NOT NULL,
  query_id int8 NOT NULL,
  row_no int4 DEFAULT 0,
  row_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (row_id)
);
CREATE INDEX IF NOT EXISTS idx_biz_query_ds_row_ds ON biz_query_dataset_row(dataset_id);
CREATE INDEX IF NOT EXISTS idx_biz_query_ds_row_qid ON biz_query_dataset_row(query_id);

CREATE TABLE IF NOT EXISTS biz_query_relation (
  relation_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  query_id int8 NOT NULL,
  left_dataset_id int8 NOT NULL,
  right_dataset_id int8 NOT NULL,
  join_type varchar(20) DEFAULT 'LEFT',
  join_keys_json text NOT NULL,
  sort int4 DEFAULT 0,
  PRIMARY KEY (relation_id)
);
CREATE INDEX IF NOT EXISTS idx_biz_query_relation_qid ON biz_query_relation(query_id);
