-- Native WeChat / QQ OAuth binding + config keys

CREATE TABLE IF NOT EXISTS biz_user_oauth (
  id           int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id      int8 NOT NULL,
  provider     varchar(16) NOT NULL,
  open_id      varchar(128) NOT NULL,
  union_id     varchar(128) DEFAULT NULL,
  nickname     varchar(64) DEFAULT NULL,
  avatar       varchar(512) DEFAULT NULL,
  create_time  timestamp DEFAULT now(),
  update_time  timestamp DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_biz_user_oauth_provider_openid UNIQUE (provider, open_id)
);

CREATE INDEX IF NOT EXISTS idx_biz_user_oauth_user_id ON biz_user_oauth (user_id);

COMMENT ON TABLE biz_user_oauth IS 'Third-party OAuth binding (wechat/qq)';
COMMENT ON COLUMN biz_user_oauth.provider IS 'wechat | qq';
COMMENT ON COLUMN biz_user_oauth.open_id IS 'Provider openid';

INSERT INTO sys_config (config_name, config_key, config_value, config_type, create_by, create_time, remark)
SELECT 'OAuth frontend redirect base', 'sys.oauth.redirectBase', 'http://127.0.0.1:1024', 'Y', 'admin', now(), 'Frontend origin for oauthTicket redirect'
WHERE NOT EXISTS (SELECT 1 FROM sys_config WHERE config_key = 'sys.oauth.redirectBase');

INSERT INTO sys_config (config_name, config_key, config_value, config_type, create_by, create_time, remark)
SELECT 'OAuth API callback base', 'sys.oauth.callbackBase', 'http://127.0.0.1:1024/dev-api', 'Y', 'admin', now(), 'Public API root for IdP redirect_uri'
WHERE NOT EXISTS (SELECT 1 FROM sys_config WHERE config_key = 'sys.oauth.callbackBase');

INSERT INTO sys_config (config_name, config_key, config_value, config_type, create_by, create_time, remark)
SELECT 'WeChat OAuth enabled', 'sys.oauth.wechat.enabled', 'false', 'Y', 'admin', now(), 'WeChat website QR login'
WHERE NOT EXISTS (SELECT 1 FROM sys_config WHERE config_key = 'sys.oauth.wechat.enabled');

INSERT INTO sys_config (config_name, config_key, config_value, config_type, create_by, create_time, remark)
SELECT 'WeChat AppID', 'sys.oauth.wechat.appId', '', 'Y', 'admin', now(), 'WeChat Open Platform website app id'
WHERE NOT EXISTS (SELECT 1 FROM sys_config WHERE config_key = 'sys.oauth.wechat.appId');

INSERT INTO sys_config (config_name, config_key, config_value, config_type, create_by, create_time, remark)
SELECT 'WeChat AppSecret', 'sys.oauth.wechat.appSecret', '', 'Y', 'admin', now(), 'WeChat website app secret'
WHERE NOT EXISTS (SELECT 1 FROM sys_config WHERE config_key = 'sys.oauth.wechat.appSecret');

INSERT INTO sys_config (config_name, config_key, config_value, config_type, create_by, create_time, remark)
SELECT 'QQ OAuth enabled', 'sys.oauth.qq.enabled', 'false', 'Y', 'admin', now(), 'QQ Connect login'
WHERE NOT EXISTS (SELECT 1 FROM sys_config WHERE config_key = 'sys.oauth.qq.enabled');

INSERT INTO sys_config (config_name, config_key, config_value, config_type, create_by, create_time, remark)
SELECT 'QQ AppID', 'sys.oauth.qq.appId', '', 'Y', 'admin', now(), 'QQ Connect app id'
WHERE NOT EXISTS (SELECT 1 FROM sys_config WHERE config_key = 'sys.oauth.qq.appId');

INSERT INTO sys_config (config_name, config_key, config_value, config_type, create_by, create_time, remark)
SELECT 'QQ AppKey', 'sys.oauth.qq.appKey', '', 'Y', 'admin', now(), 'QQ Connect app key'
WHERE NOT EXISTS (SELECT 1 FROM sys_config WHERE config_key = 'sys.oauth.qq.appKey');
