-- ----------------------------
-- 通查云 biz tables (PostgreSQL)
-- ----------------------------

drop table if exists biz_survey_answer_item cascade;
drop table if exists biz_survey_answer cascade;
drop table if exists biz_survey_question cascade;
drop table if exists biz_survey cascade;
drop table if exists biz_query_page cascade;
drop table if exists biz_query_row cascade;
drop table if exists biz_query_field cascade;
drop table if exists biz_query cascade;

create table biz_query (
  query_id int8 generated by default as identity not null,
  query_name varchar(100) not null,
  query_desc varchar(500) default '',
  public_code varchar(32) default null,
  status char(1) default '0',
  source_file varchar(255) default null,
  sheet_name varchar(100) default null,
  row_count int4 default 0,
  access_pwd varchar(64) default null,
  view_count int8 default 0,
  search_count int8 default 0,
  parse_status char(1) default '0',
  parse_msg varchar(500) default null,
  create_user_id int8 default null,
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  primary key (query_id)
);
create unique index uk_biz_query_code on biz_query(public_code) where public_code is not null;
create index idx_biz_query_user on biz_query(create_user_id);
comment on table biz_query is '查询项目';

create table biz_query_field (
  field_id int8 generated by default as identity not null,
  query_id int8 not null,
  field_key varchar(64) not null,
  field_name varchar(100) default '',
  field_label varchar(100) default '',
  data_type varchar(20) default 'string',
  is_query char(1) default '0',
  query_type varchar(20) default 'EQ',
  html_type varchar(20) default 'input',
  is_list char(1) default '1',
  is_sortable char(1) default '0',
  dict_options text,
  sort int4 default 0,
  width int4 default null,
  primary key (field_id)
);
create index idx_biz_query_field_qid on biz_query_field(query_id);
comment on table biz_query_field is '查询字段配置';

create table biz_query_row (
  row_id int8 generated by default as identity not null,
  query_id int8 not null,
  row_no int4 default 0,
  row_data jsonb not null default '{}'::jsonb,
  primary key (row_id)
);
create index idx_biz_query_row_qid on biz_query_row(query_id);
create index idx_biz_query_row_qid_rowno on biz_query_row(query_id, row_no);
create index idx_biz_query_row_data_gin on biz_query_row using gin (row_data jsonb_path_ops);
create index idx_biz_query_row_data on biz_query_row using gin(row_data);
comment on table biz_query_row is '查询行数据';

create table biz_query_page (
  page_id int8 generated by default as identity not null,
  query_id int8 not null,
  title varchar(100) default '',
  subtitle varchar(255) default '',
  theme_color varchar(20) default '#1677ff',
  banner_url varchar(255) default null,
  layout_json text,
  result_tips varchar(255) default '',
  primary key (page_id),
  constraint uk_biz_query_page unique (query_id)
);
comment on table biz_query_page is '查询页面设计';

create table biz_survey (
  survey_id int8 generated by default as identity not null,
  survey_name varchar(100) not null,
  survey_desc varchar(500) default '',
  public_code varchar(32) default null,
  status char(1) default '0',
  start_time timestamp,
  end_time timestamp,
  max_answers int4 default 0,
  allow_multi char(1) default '1',
  access_pwd varchar(64) default null,
  theme_json text,
  webhook_url varchar(500) default null,
  view_count int8 default 0,
  answer_count int8 default 0,
  create_user_id int8 default null,
  create_by varchar(64) default '',
  create_time timestamp,
  update_by varchar(64) default '',
  update_time timestamp,
  remark varchar(500) default null,
  primary key (survey_id)
);
create unique index uk_biz_survey_code on biz_survey(public_code) where public_code is not null;
create index idx_biz_survey_user on biz_survey(create_user_id);
comment on table biz_survey is '问卷项目';

create table biz_survey_question (
  question_id int8 generated by default as identity not null,
  survey_id int8 not null,
  q_type varchar(20) not null,
  title varchar(500) not null,
  required char(1) default '0',
  options_json text,
  props_json text,
  sort int4 default 0,
  primary key (question_id)
);
create index idx_biz_survey_question_sid on biz_survey_question(survey_id);
comment on table biz_survey_question is '问卷题目';

create table biz_survey_answer (
  answer_id int8 generated by default as identity not null,
  survey_id int8 not null,
  submit_ip varchar(128) default '',
  submit_ua varchar(500) default '',
  submit_time timestamp,
  cost_ms int4 default 0,
  primary key (answer_id)
);
create index idx_biz_survey_answer_sid on biz_survey_answer(survey_id);
comment on table biz_survey_answer is '问卷答卷';

create table biz_survey_answer_item (
  item_id int8 generated by default as identity not null,
  answer_id int8 not null,
  question_id int8 not null,
  answer_value text,
  primary key (item_id)
);
create index idx_biz_survey_answer_item_aid on biz_survey_answer_item(answer_id);
comment on table biz_survey_answer_item is '答卷明细';

create table biz_survey_notify (
  notify_id int8 generated by default as identity not null,
  user_id int8 not null,
  survey_id int8 not null,
  answer_id int8 default null,
  title varchar(200) not null,
  content varchar(500) default '',
  read_flag char(1) default '0',
  create_time timestamp default now(),
  primary key (notify_id)
);
create index idx_biz_survey_notify_user on biz_survey_notify(user_id, read_flag, notify_id DESC);
comment on table biz_survey_notify is '问卷答卷站内通知';

-- ----------------------------
-- Menus (ids from 2000)
-- ----------------------------
-- remove old biz menus if re-run
delete from sys_role_menu where menu_id between 2000 and 2099;
delete from sys_menu where menu_id between 2000 and 2099;

insert into sys_menu values(2000, '业务中心', '0', '5', 'biz', null, '', '', 1, 0, 'M', '0', '0', '', 'component', 'admin', now(), '', null, '业务中心目录');
insert into sys_menu values(2003, '业务看板', '2000', '0', 'dashboard', 'biz/dashboard/index', '', '', 1, 0, 'C', '0', '0', 'biz:dashboard:list', 'chart', 'admin', now(), '', null, '业务看板');
insert into sys_menu values(2001, '查询管理', '2000', '1', 'query', 'biz/query/index', '', '', 1, 0, 'C', '0', '0', 'biz:query:list', 'search', 'admin', now(), '', null, '查询管理菜单');
insert into sys_menu values(2002, '问卷管理', '2000', '2', 'survey', 'biz/survey/index', '', '', 1, 0, 'C', '0', '0', 'biz:survey:list', 'form', 'admin', now(), '', null, '问卷管理菜单');

-- query buttons
insert into sys_menu values(2010, '查询查询', '2001', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'biz:query:query', '#', 'admin', now(), '', null, '');
insert into sys_menu values(2011, '查询新增', '2001', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'biz:query:add', '#', 'admin', now(), '', null, '');
insert into sys_menu values(2012, '查询修改', '2001', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'biz:query:edit', '#', 'admin', now(), '', null, '');
insert into sys_menu values(2013, '查询删除', '2001', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'biz:query:remove', '#', 'admin', now(), '', null, '');
insert into sys_menu values(2014, '查询发布', '2001', '5', '', '', '', '', 1, 0, 'F', '0', '0', 'biz:query:publish', '#', 'admin', now(), '', null, '');

-- survey buttons
insert into sys_menu values(2020, '问卷查询', '2002', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'biz:survey:query', '#', 'admin', now(), '', null, '');
insert into sys_menu values(2021, '问卷新增', '2002', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'biz:survey:add', '#', 'admin', now(), '', null, '');
insert into sys_menu values(2022, '问卷修改', '2002', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'biz:survey:edit', '#', 'admin', now(), '', null, '');
insert into sys_menu values(2023, '问卷删除', '2002', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'biz:survey:remove', '#', 'admin', now(), '', null, '');
insert into sys_menu values(2024, '问卷发布', '2002', '5', '', '', '', '', 1, 0, 'F', '0', '0', 'biz:survey:publish', '#', 'admin', now(), '', null, '');

-- grant to admin role
insert into sys_role_menu (role_id, menu_id)
select 1, menu_id from sys_menu where menu_id between 2000 and 2099;

-- dict types
delete from sys_dict_data where dict_type in ('biz_query_status', 'biz_survey_status', 'biz_question_type');
delete from sys_dict_type where dict_type in ('biz_query_status', 'biz_survey_status', 'biz_question_type');

insert into sys_dict_type values(100, '查询状态', 'biz_query_status', '0', 'admin', now(), '', null, '查询项目状态');
insert into sys_dict_type values(101, '问卷状态', 'biz_survey_status', '0', 'admin', now(), '', null, '问卷项目状态');
insert into sys_dict_type values(102, '问卷题型', 'biz_question_type', '0', 'admin', now(), '', null, '问卷题目类型');

insert into sys_dict_data values(200, 1, '草稿', '0', 'biz_query_status', '', 'info', 'Y', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(201, 2, '已发布', '1', 'biz_query_status', '', 'success', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(202, 3, '已停用', '2', 'biz_query_status', '', 'danger', 'N', '0', 'admin', now(), '', null, '');

insert into sys_dict_data values(210, 1, '草稿', '0', 'biz_survey_status', '', 'info', 'Y', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(211, 2, '已发布', '1', 'biz_survey_status', '', 'success', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(212, 3, '已停用', '2', 'biz_survey_status', '', 'warning', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(213, 4, '已结束', '3', 'biz_survey_status', '', 'danger', 'N', '0', 'admin', now(), '', null, '');

insert into sys_dict_data values(220, 1, '单选', 'radio', 'biz_question_type', '', 'default', 'Y', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(221, 2, '多选', 'checkbox', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(222, 3, '单行填空', 'input', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(223, 4, '多行填空', 'textarea', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(224, 5, '下拉', 'select', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(225, 6, '评分', 'rate', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(226, 7, '日期', 'date', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(227, 8, '手机号', 'phone', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(228, 9, '附件上传', 'file', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '');
insert into sys_dict_data values(229, 10, '是非题', 'yesno', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '是/否');
insert into sys_dict_data values(230, 11, '数字', 'number', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '数字输入');
insert into sys_dict_data values(231, 12, 'NPS', 'nps', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '净推荐值0-10');
insert into sys_dict_data values(232, 13, '说明段落', 'section', 'biz_question_type', '', 'info', 'N', '0', 'admin', now(), '', null, '展示说明');
insert into sys_dict_data values(233, 14, '邮箱', 'email', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '邮箱');
insert into sys_dict_data values(234, 15, '日期时间', 'datetime', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '日期时间');
insert into sys_dict_data values(235, 16, '滑块', 'slider', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '滑块');
insert into sys_dict_data values(236, 17, '图片单选', 'image_radio', 'biz_question_type', '', 'default', 'N', '0', 'admin', now(), '', null, '图片单选');


select setval(pg_get_serial_sequence('sys_dict_type', 'dict_id'), greatest(coalesce((select max(dict_id) from sys_dict_type), 1), 102));
select setval(pg_get_serial_sequence('sys_dict_data', 'dict_code'), greatest(coalesce((select max(dict_code) from sys_dict_data), 1), 236));
select setval(pg_get_serial_sequence('sys_menu', 'menu_id'), greatest(coalesce((select max(menu_id) from sys_menu), 1), 2099));
