-- Phase 10: survey inbox notifications
CREATE TABLE IF NOT EXISTS biz_survey_notify (
  notify_id int8 generated by default as identity not null,
  user_id int8 not null,
  survey_id int8 not null,
  answer_id int8 default null,
  title varchar(200) not null,
  content varchar(500) default '',
  read_flag char(1) default '0',
  create_time timestamp default now(),
  primary key (notify_id)
);
CREATE INDEX IF NOT EXISTS idx_biz_survey_notify_user ON biz_survey_notify(user_id, read_flag, notify_id DESC);
COMMENT ON TABLE biz_survey_notify IS '问卷答卷站内通知';
