-- Phase 13: public access log for UV + open export support
CREATE TABLE IF NOT EXISTS biz_access_log (
  log_id int8 generated by default as identity not null,
  target_type varchar(20) not null,
  target_id int8 not null,
  public_code varchar(32) default null,
  action varchar(20) not null,
  client_ip varchar(64) default '',
  user_agent varchar(500) default '',
  create_time timestamp default now(),
  primary key (log_id)
);
CREATE INDEX IF NOT EXISTS idx_biz_access_log_target ON biz_access_log(target_type, target_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_biz_access_log_uv ON biz_access_log(target_type, action, create_time, client_ip);
COMMENT ON TABLE biz_access_log IS 'public access log for PV/UV';
