#!/usr/bin/env python3
"""Convert RuoYi MySQL SQL scripts to PostgreSQL."""
import re
from pathlib import Path

BASE = Path(__file__).resolve().parent


def esc(s: str) -> str:
    return s.replace("'", "''")


def convert_ry(src_text: str) -> str:
    table_comments: dict[str, str] = {}
    column_comments: list[tuple[str, str, str]] = []
    auto_starts: dict[str, int] = {}

    for m in re.finditer(
        r"create\s+table\s+(\w+)\s*\(.*?\)\s*engine=innodb\s+auto_increment=(\d+)\s*comment",
        src_text,
        re.I | re.S,
    ):
        auto_starts[m.group(1)] = int(m.group(2))

    indexes: list[str] = []

    def convert_create(match: re.Match) -> str:
        tname = match.group(1)
        body = match.group(2)
        tcomment = match.group(3)
        table_comments[tname] = tcomment
        lines_out: list[str] = []
        for raw in body.split("\n"):
            stripped = raw.strip()
            if not stripped:
                continue
            uk = re.match(
                r"unique\s+key\s+(\w+)\s*\(([^)]+)\)(?:\s+comment\s+'([^']*)')?",
                stripped,
                re.I,
            )
            if uk:
                lines_out.append(f"  constraint {uk.group(1)} unique ({uk.group(2)}),")
                continue
            idx = re.match(r"(?:key|index)\s+(\w+)\s*\(([^)]+)\)", stripped, re.I)
            if idx:
                indexes.append(
                    f"create index if not exists {idx.group(1)} on {tname} ({idx.group(2)});"
                )
                continue
            if re.match(r"primary\s+key", stripped, re.I):
                lines_out.append("  " + stripped.rstrip(",") + ",")
                continue
            cm = re.search(r"\s+comment\s+'([^']*)'\s*,?\s*$", stripped, re.I)
            comment = cm.group(1) if cm else None
            col_def = re.sub(r"\s+comment\s+'[^']*'\s*,?\s*$", "", stripped, flags=re.I)
            col_def = col_def.rstrip(",").strip().replace("`", "")
            cname = col_def.split()[0]
            if comment and cname.lower() not in ("primary", "unique", "key", "constraint"):
                column_comments.append((tname, cname, comment))
            has_ai = bool(re.search(r"\bauto_increment\b", col_def, re.I))
            col_def = re.sub(r"\bauto_increment\b", "", col_def, flags=re.I)
            col_def = re.sub(r"\bbigint\(\d+\)", "int8", col_def, flags=re.I)
            col_def = re.sub(r"\bint\(\d+\)", "int4", col_def, flags=re.I)
            col_def = re.sub(r"\bsmallint\(\d+\)", "int2", col_def, flags=re.I)
            col_def = re.sub(r"\btinyint\(\d+\)", "int2", col_def, flags=re.I)
            col_def = re.sub(r"\bdatetime\b", "timestamp", col_def, flags=re.I)
            col_def = re.sub(r"\blongblob\b", "text", col_def, flags=re.I)
            col_def = re.sub(r"\blongtext\b", "text", col_def, flags=re.I)
            col_def = re.sub(r"\bblob\b", "bytea", col_def, flags=re.I)
            col_def = re.sub(r"\s+", " ", col_def).strip()
            if has_ai:
                parts = col_def.split(" ", 2)
                rest = parts[2] if len(parts) > 2 else ""
                col_def = f"{parts[0]} {parts[1]} generated by default as identity {rest}".strip()
            lines_out.append(f"  {col_def},")
        if lines_out:
            lines_out[-1] = lines_out[-1].rstrip(",")
        return f"create table {tname} (\n" + "\n".join(lines_out) + "\n);"

    pattern = re.compile(
        r"create\s+table\s+(\w+)\s*\((.*?)\)\s*engine=innodb(?:\s+auto_increment=\d+)?\s*comment\s*=?\s*'([^']*)'\s*;",
        re.I | re.S,
    )
    new_sql = pattern.sub(convert_create, src_text)
    if indexes:
        new_sql += "\n\n-- ----------------------------\n-- Indexes\n-- ----------------------------\n"
        new_sql += "\n".join(indexes) + "\n"
    # Fix char/varchar defaults that used unquoted numbers from MySQL
    new_sql = re.sub(
        r"(char\(\d+\)\s+default)\s+(\d+)\b",
        r"\1 '\2'",
        new_sql,
        flags=re.I,
    )
    new_sql = re.sub(r"\bsysdate\(\)", "now()", new_sql, flags=re.I)
    # MySQL C-style escapes -> standard SQL
    new_sql = new_sql.replace(r"\'", "''").replace(r"\"", '"')
    new_sql = re.sub(
        r"drop\s+table\s+if\s+exists\s+(\w+)\s*;",
        r"drop table if exists \1 cascade;",
        new_sql,
        flags=re.I,
    )

    comments_sql = [
        "",
        "-- ----------------------------",
        "-- Comments & identity sequences",
        "-- ----------------------------",
    ]
    for t, c in table_comments.items():
        comments_sql.append(f"comment on table {t} is '{esc(c)}';")
    for t, col, c in column_comments:
        comments_sql.append(f"comment on column {t}.{col} is '{esc(c)}';")

    setval_tables = {
        "sys_dept": 200,
        "sys_user": 100,
        "sys_post": None,
        "sys_role": None,
        "sys_menu": None,
        "sys_oper_log": 100,
        "sys_dict_type": 100,
        "sys_dict_data": 100,
        "sys_config": 100,
        "sys_logininfor": 100,
        "sys_job": 100,
        "sys_job_log": None,
        "sys_notice": 10,
        "sys_notice_read": 1,
        "gen_table": 1,
        "gen_table_column": 1,
    }
    setval_tables.update(auto_starts)

    pk_map = {
        "sys_dept": "dept_id",
        "sys_user": "user_id",
        "sys_post": "post_id",
        "sys_role": "role_id",
        "sys_menu": "menu_id",
        "sys_oper_log": "oper_id",
        "sys_dict_type": "dict_id",
        "sys_dict_data": "dict_code",
        "sys_config": "config_id",
        "sys_logininfor": "info_id",
        "sys_job": "job_id",
        "sys_job_log": "job_log_id",
        "sys_notice": "notice_id",
        "sys_notice_read": "read_id",
        "gen_table": "table_id",
        "gen_table_column": "column_id",
    }

    comments_sql.append("")
    comments_sql.append("-- Reset identity sequences after seed data")
    for t, start in setval_tables.items():
        pk = pk_map.get(t)
        if not pk:
            continue
        if start is None:
            comments_sql.append(
                f"select setval(pg_get_serial_sequence('{t}', '{pk}'), "
                f"coalesce((select max({pk}) from {t}), 1), true);"
            )
        else:
            comments_sql.append(
                f"select setval(pg_get_serial_sequence('{t}', '{pk}'), "
                f"greatest(coalesce((select max({pk}) from {t}), 1), {start - 1}));"
            )

    out = new_sql + "\n" + "\n".join(comments_sql) + "\n"
    assert "engine=innodb" not in out.lower()
    assert "auto_increment" not in out.lower()
    assert "sysdate" not in out.lower()
    return out


def convert_quartz(src_text: str) -> str:
    def convert_create(match: re.Match) -> str:
        tname = match.group(1)
        body = match.group(2)
        lines_out: list[str] = []
        for raw in body.split("\n"):
            stripped = raw.strip()
            if not stripped:
                continue
            if re.match(r"primary\s+key", stripped, re.I) or re.match(
                r"foreign\s+key", stripped, re.I
            ):
                lines_out.append("  " + stripped.rstrip(",") + ",")
                continue
            col_def = re.sub(r"\s+comment\s+'[^']*'\s*,?\s*$", "", stripped, flags=re.I)
            col_def = col_def.rstrip(",").strip()
            col_def = re.sub(r"\bbigint\(\d+\)", "int8", col_def, flags=re.I)
            col_def = re.sub(r"\bsmallint\(\d+\)", "int2", col_def, flags=re.I)
            col_def = re.sub(r"\bblob\b", "bytea", col_def, flags=re.I)
            col_def = re.sub(r"\s+", " ", col_def).strip()
            lines_out.append(f"  {col_def},")
        if lines_out:
            lines_out[-1] = lines_out[-1].rstrip(",")
        return f"create table {tname} (\n" + "\n".join(lines_out) + "\n);"

    pattern = re.compile(
        r"create\s+table\s+(\w+)\s*\((.*?)\)\s*engine=innodb\s*comment\s*=\s*'([^']*)'\s*;",
        re.I | re.S,
    )
    new_sql = pattern.sub(convert_create, src_text)
    new_sql = re.sub(
        r"drop\s+table\s+if\s+exists\s+(\w+)\s*;",
        r"drop table if exists \1 cascade;",
        new_sql,
        flags=re.I,
    )
    assert "engine=innodb" not in new_sql.lower()
    return new_sql


def main() -> None:
    ry = convert_ry((BASE / "ry_20260417.sql").read_text(encoding="utf-8"))
    (BASE / "ry_postgresql.sql").write_text(ry, encoding="utf-8")
    print(f"Wrote ry_postgresql.sql ({len(ry)} bytes)")

    qz = convert_quartz((BASE / "quartz.sql").read_text(encoding="utf-8"))
    (BASE / "quartz_postgresql.sql").write_text(qz, encoding="utf-8")
    print(f"Wrote quartz_postgresql.sql ({len(qz)} bytes)")


if __name__ == "__main__":
    main()
